apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.name }}
type: Opaque
stringData:
  config.yaml: |-
    webhook:
      enabled: {{ .Values.config.webhook.enabled }}
      url: {{ .Values.config.webhook.url }}

    slack:
      enabled: {{ .Values.config.slack.enabled }}
      url: {{ .Values.config.slack.url }}

    telegram:
      enabled: {{ .Values.config.telegram.enabled }}
      token: {{ .Values.config.telegram.token }}
      chatID: {{ .Values.config.telegram.chatID }}

    excluded.reasons: {{ .Values.config.excluded.reasons   }}

    included.reasons: {{ .Values.config.included.reasons }}

