apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.name }}
type: Opaque
stringData:
  config.yaml: |-
    webhook:
      enabled: {{ .Values.config.webhook.enabled }}
      url: {{ .Values.config.webhook.url }}

    slack:
      enabled: {{ .Values.config.slack.enabled }}
      url: {{ .Values.config.slack.url }}

    telegram:
      enabled: {{ .Values.config.telegram.enabled }}
      token: {{ .Values.config.telegram.url }}
      chat.id: {{ .Values.config.chat.id }}

    excluded.reasons: []

    included.reasons: ["ScalingReplicaSet", "Started", "Killing"]


