metadata:
  name: siera-kube-watch

image:
  repository: warungpintar/siera-kube-watch
  pullPolicy: Always
  tag: v1.0.0

config:
  webhook:
    enabled: false
    url: http://webhookurl

  slack:
    enabled: false
    url: http://slackurl

  telegram:
    enabled: false
    token: http://slackurl
    chatID: -1234567890123


  excluded:
    reasons: '[]'
  included:
    reasons: '["ScalingReplicaSet", "Started", "Killing"]'


